INSERT INTO tAddress (addrStrasse, addrNummer, addrPLZ, addrOrt, addrLand) VALUES ('Birchwood', '5', '67 896', 'Aasdk', 'BI');
INSERT INTO tAddress (addrStrasse, addrNummer, addrPLZ, addrOrt, addrLand) VALUES ('Eagle Crest', '38684', '531 85', 'Västra Götaland', 'SE');
INSERT INTO tAddress (addrStrasse, addrNummer, addrPLZ, addrOrt, addrLand) VALUES ('Barnett', '22', '765 02', 'Uztajn', 'CZ');
INSERT INTO tAddress (addrStrasse, addrNummer, addrPLZ, addrOrt, addrLand) VALUES ('Del Mar', '89', '501 83', 'Västra Götaland', 'SE');
INSERT INTO tAddress (addrStrasse, addrNummer, addrPLZ, addrOrt, addrLand) VALUES ('Bartelt', '99', '9812 98', 'Waskjed', 'ID');
INSERT INTO tAddress (addrStrasse, addrNummer, addrPLZ, addrOrt, addrLand) VALUES ('Farmco', '18542', '51242', 'Muzahsd', 'HR');
INSERT INTO tAddress (addrStrasse, addrNummer, addrPLZ, addrOrt, addrLand) VALUES ('Bartillon', '307', '735 32', 'Clköajse', 'CZ');
INSERT INTO tAddress (addrStrasse, addrNummer, addrPLZ, addrOrt, addrLand) VALUES ('La Follette', '66', '22908', 'Virginia', 'US');
INSERT INTO tAddress (addrStrasse, addrNummer, addrPLZ, addrOrt, addrLand) VALUES ('Cambridge', '95823', '7890', 'Tzujnm', 'UA');
INSERT INTO tAddress (addrStrasse, addrNummer, addrPLZ, addrOrt, addrLand) VALUES ('Maple', '3', '67812', 'Gvgbkl', 'PS');
INSERT INTO tAddress (addrStrasse, addrNummer, addrPLZ, addrOrt, addrLand) VALUES ('Myrtle', '33', '162798', 'Klöj Aas', 'GR');
INSERT INTO tAddress (addrStrasse, addrNummer, addrPLZ, addrOrt, addrLand) VALUES ('Del Mar', '3', '809132', 'Öljkas', 'EG');
INSERT INTO tAddress (addrStrasse, addrNummer, addrPLZ, addrOrt, addrLand) VALUES ('Hudson', '363', '80149', 'Tlkaöl', 'AM', 'DE');
INSERT INTO tAddress (addrStrasse, addrNummer, addrPLZ, addrOrt, addrLand) VALUES ('Saint Paul', '9526', '43560', 'LKéJ Aed', 'IL');
INSERT INTO tAddress (addrStrasse, addrNummer, addrPLZ, addrOrt, addrLand) VALUES ('Glendale', '441', '2402', 'Kaneiemä', 'PH');
INSERT INTO tAddress (addrStrasse, addrNummer, addrPLZ, addrOrt, addrLand) VALUES ('Fair Oaks', '29857', '128709', 'Mnaikmeu', 'ID');
INSERT INTO tAddress (addrStrasse, addrNummer, addrPLZ, addrOrt, addrLand) VALUES ('Oneill', '044', '8301', 'Mauekruö', 'PH');
INSERT INTO tAddress (addrStrasse, addrNummer, addrPLZ, addrOrt, addrLand) VALUES ('David', '42387', '77645-000', 'Naeinei', 'BR');
INSERT INTO tAddress (addrStrasse, addrNummer, addrPLZ, addrOrt, addrLand) VALUES ('Columbus', '9861', '458632', 'Neinepoän', 'ID');
INSERT INTO tAddress (addrStrasse, addrNummer, addrPLZ, addrOrt, addrLand) VALUES ('Shoshone', '51', '10573', 'Nasdlköje', 'ID');
INSERT INTO tAddress (addrStrasse, addrNummer, addrPLZ, addrOrt, addrLand) VALUES ('Blackbird', '98', '45306', 'Jalisco', 'MX');
INSERT INTO tAddress (addrStrasse, addrNummer, addrPLZ, addrOrt, addrLand) VALUES ('Birchwood', '4916', '404109', 'Jemknceza', 'RU');
INSERT INTO tAddress (addrStrasse, addrNummer, addrPLZ, addrOrt, addrLand) VALUES ('Tony', '64799', '20567', 'Nemüamöer', 'ID');
INSERT INTO tAddress (addrStrasse, addrNummer, addrPLZ, addrOrt, addrLand) VALUES ('Linden', '33112', '39', 'Nlökeaneun', 'CN');
INSERT INTO tAddress (addrStrasse, addrNummer, addrPLZ, addrOrt, addrLand) VALUES ('Service', '1241', '3067', 'Huezanmez', 'CN');
INSERT INTO tAddress (addrStrasse, addrNummer, addrPLZ, addrOrt, addrLand) VALUES ('Graedel', '92920', '1493', 'Naekl', 'SV');
INSERT INTO tAddress (addrStrasse, addrNummer, addrPLZ, addrOrt, addrLand) VALUES ('Schurz', '546', '2890-206', 'Setúbal', 'PT');
INSERT INTO tAddress (addrStrasse, addrNummer, addrPLZ, addrOrt, addrLand) VALUES ('School', '92396', '28949', 'Umeunae', 'ID');
INSERT INTO tAddress (addrStrasse, addrNummer, addrPLZ, addrOrt, addrLand) VALUES ('Kedzie', '011', '309379', 'Rmzethak', 'RU');
INSERT INTO tAddress (addrStrasse, addrNummer, addrPLZ, addrOrt, addrLand) VALUES ('Riverside', '3', '18500-000', 'Zzkasa', 'BR');
