INSERT INTO tBuch (shTimeId, langId, infoId, availableId, publisherId, priceId, placeId) VALUES (20, 1, 18, 2, 8, 1, 1);
INSERT INTO tBuch (shTimeId, langId, infoId, availableId, publisherId, priceId, placeId) VALUES (19, 9, 4, 2, 17, 2, 2);
INSERT INTO tBuch (shTimeId, langId, infoId, availableId, publisherId, priceId, placeId) VALUES (30, 7, 38, 2, 18, 3, 3);
INSERT INTO tBuch (shTimeId, langId, infoId, availableId, publisherId, priceId, placeId) VALUES (25, 24, 8, 2, 13, 4, 4);
INSERT INTO tBuch (shTimeId, langId, infoId, availableId, publisherId, priceId, placeId) VALUES (10, 24, 42, 2, 5, 5, 5);
INSERT INTO tBuch (shTimeId, langId, infoId, availableId, publisherId, priceId, placeId) VALUES (16, 24, 29, 2, 6, 6, 6);
INSERT INTO tBuch (shTimeId, langId, infoId, availableId, publisherId, priceId, placeId) VALUES (29, 7, 24, 1, 11, 7, 7);
INSERT INTO tBuch (shTimeId, langId, infoId, availableId, publisherId, priceId, placeId) VALUES ( 9, 7, 34, 2, 19, 8, 8);
INSERT INTO tBuch (shTimeId, langId, infoId, availableId, publisherId, priceId, placeId) VALUES ( 9, 9, 36, 2, 11, 9, 9);
INSERT INTO tBuch (shTimeId, langId, infoId, availableId, publisherId, priceId, placeId) VALUES (13, 9, 14, 2, 8, 10, 10);
INSERT INTO tBuch (shTimeId, langId, infoId, availableId, publisherId, priceId, placeId) VALUES (30, 25, 13, 2, 22, 11, 11);
INSERT INTO tBuch (shTimeId, langId, infoId, availableId, publisherId, priceId, placeId) VALUES ( 4, 17, 49, 1, 20, 12, 12);
INSERT INTO tBuch (shTimeId, langId, infoId, availableId, publisherId, priceId, placeId) VALUES (28, 28, 2, 2, 23, 13, 13);
INSERT INTO tBuch (shTimeId, langId, infoId, availableId, publisherId, priceId, placeId) VALUES (30, 8, 19, 2, 20, 14, 14);
INSERT INTO tBuch (shTimeId, langId, infoId, availableId, publisherId, priceId, placeId) VALUES (14, 21, 21, 2, 16, 15, 15);
INSERT INTO tBuch (shTimeId, langId, infoId, availableId, publisherId, priceId, placeId) VALUES (18, 9, 11, 2, 24, 16, 16);
INSERT INTO tBuch (shTimeId, langId, infoId, availableId, publisherId, priceId, placeId) VALUES (10, 14, 12, 1, 30, 17, 17);
INSERT INTO tBuch (shTimeId, langId, infoId, availableId, publisherId, priceId, placeId) VALUES (14, 28, 8, 2, 15, 18, 18);
INSERT INTO tBuch (shTimeId, langId, infoId, availableId, publisherId, priceId, placeId) VALUES (30, 22, 9, 2, 7, 19, 19);
INSERT INTO tBuch (shTimeId, langId, infoId, availableId, publisherId, priceId, placeId) VALUES (12, 18, 45, 2, 9, 20, 20);
INSERT INTO tBuch (shTimeId, langId, infoId, availableId, publisherId, priceId, placeId) VALUES (28, 29, 6, 2, 16, 21, 21);
INSERT INTO tBuch (shTimeId, langId, infoId, availableId, publisherId, priceId, placeId) VALUES (18, 8, 11, 2, 4, 22, 22);
INSERT INTO tBuch (shTimeId, langId, infoId, availableId, publisherId, priceId, placeId) VALUES (12, 19, 2, 2, 27, 23, 23);
INSERT INTO tBuch (shTimeId, langId, infoId, availableId, publisherId, priceId, placeId) VALUES (23, 6, 27, 2, 22, 24, 24);
INSERT INTO tBuch (shTimeId, langId, infoId, availableId, publisherId, priceId, placeId) VALUES ( 7, 10, 7, 2, 23, 25, 25);
INSERT INTO tBuch (shTimeId, langId, infoId, availableId, publisherId, priceId, placeId) VALUES (23, 4, 50, 2, 16, 26, 26);
INSERT INTO tBuch (shTimeId, langId, infoId, availableId, publisherId, priceId, placeId) VALUES (25, 23, 23, 2, 30, 27, 27);
INSERT INTO tBuch (shTimeId, langId, infoId, availableId, publisherId, priceId, placeId) VALUES (16, 18, 35, 1, 2, 28, 28);
INSERT INTO tBuch (shTimeId, langId, infoId, availableId, publisherId, priceId, placeId) VALUES (13, 28, 37, 2, 19, 29, 29);
INSERT INTO tBuch (shTimeId, langId, infoId, availableId, publisherId, priceId, placeId) VALUES ( 3, 11, 10, 2, 24, 30, 30);
