INSERT INTO tShipmentTime (shTimeId, lieferfrist) VALUES (1, '1 D');
INSERT INTO tShipmentTime (shTimeId, lieferfrist) VALUES (2, '2 D');
INSERT INTO tShipmentTime (shTimeId, lieferfrist) VALUES (3, '3 D');
INSERT INTO tShipmentTime (shTimeId, lieferfrist) VALUES (4, '4 D');
INSERT INTO tShipmentTime (shTimeId, lieferfrist) VALUES (5, '5 D');
INSERT INTO tShipmentTime (shTimeId, lieferfrist) VALUES (6, '6 D');
INSERT INTO tShipmentTime (shTimeId, lieferfrist) VALUES (7, '7 D');
INSERT INTO tShipmentTime (shTimeId, lieferfrist) VALUES (8, '8 D');
INSERT INTO tShipmentTime (shTimeId, lieferfrist) VALUES (9, '9 D');
INSERT INTO tShipmentTime (shTimeId, lieferfrist) VALUES (10, '10 D');
INSERT INTO tShipmentTime (shTimeId, lieferfrist) VALUES (11, '11 D');
INSERT INTO tShipmentTime (shTimeId, lieferfrist) VALUES (12, '12 D');
INSERT INTO tShipmentTime (shTimeId, lieferfrist) VALUES (13, '13 D');
INSERT INTO tShipmentTime (shTimeId, lieferfrist) VALUES (14, '14 D');
INSERT INTO tShipmentTime (shTimeId, lieferfrist) VALUES (15, '15 D');
INSERT INTO tShipmentTime (shTimeId, lieferfrist) VALUES (16, '16 D');
INSERT INTO tShipmentTime (shTimeId, lieferfrist) VALUES (17, '17 D');
INSERT INTO tShipmentTime (shTimeId, lieferfrist) VALUES (18, '18 D');
INSERT INTO tShipmentTime (shTimeId, lieferfrist) VALUES (19, '19 D');
INSERT INTO tShipmentTime (shTimeId, lieferfrist) VALUES (20, '20 D');
INSERT INTO tShipmentTime (shTimeId, lieferfrist) VALUES (21, '21 D');
INSERT INTO tShipmentTime (shTimeId, lieferfrist) VALUES (22, '22 D');
INSERT INTO tShipmentTime (shTimeId, lieferfrist) VALUES (23, '23 D');
INSERT INTO tShipmentTime (shTimeId, lieferfrist) VALUES (24, '24 D');
INSERT INTO tShipmentTime (shTimeId, lieferfrist) VALUES (25, '25 D');
INSERT INTO tShipmentTime (shTimeId, lieferfrist) VALUES (26, '26 D');
INSERT INTO tShipmentTime (shTimeId, lieferfrist) VALUES (27, '27 D');
INSERT INTO tShipmentTime (shTimeId, lieferfrist) VALUES (28, '28 D');
INSERT INTO tShipmentTime (shTimeId, lieferfrist) VALUES (29, '29 D');
INSERT INTO tShipmentTime (shTimeId, lieferfrist) VALUES (30, '30 D');


INSERT INTO tLanguage (langId, sprache) VALUES (1, 'English');
INSERT INTO tLanguage (langId, sprache) VALUES (2, 'German');
INSERT INTO tLanguage (langId, sprache) VALUES (3, 'French');
INSERT INTO tLanguage (langId, sprache) VALUES (4, 'Italian');
INSERT INTO tLanguage (langId, sprache) VALUES (5, 'Cantonese');
INSERT INTO tLanguage (langId, sprache) VALUES (6, 'Spanish');
INSERT INTO tLanguage (langId, sprache) VALUES (7, 'Russian');
INSERT INTO tLanguage (langId, sprache) VALUES (8, 'Portuguese');
INSERT INTO tLanguage (langId, sprache) VALUES (9, 'Dutch');
INSERT INTO tLanguage (langId, sprache) VALUES (10, 'Turkish');
INSERT INTO tLanguage (langId, sprache) VALUES (11, 'Swedish');
INSERT INTO tLanguage (langId, sprache) VALUES (12, 'Polish');
INSERT INTO tLanguage (langId, sprache) VALUES (13, 'Norwegian');
INSERT INTO tLanguage (langId, sprache) VALUES (14, 'Danish');
INSERT INTO tLanguage (langId, sprache) VALUES (15, 'Indonesian');
INSERT INTO tLanguage (langId, sprache) VALUES (16, 'Japanese');
INSERT INTO tLanguage (langId, sprache) VALUES (17, 'Bengali');
INSERT INTO tLanguage (langId, sprache) VALUES (18, 'Hindi');
INSERT INTO tLanguage (langId, sprache) VALUES (19, 'Punjabi');
INSERT INTO tLanguage (langId, sprache) VALUES (20, 'Mandarin');
INSERT INTO tLanguage (langId, sprache) VALUES (21, 'Malay');
INSERT INTO tLanguage (langId, sprache) VALUES (22, 'Korean');
INSERT INTO tLanguage (langId, sprache) VALUES (23, 'Vietnamese');
INSERT INTO tLanguage (langId, sprache) VALUES (24, 'Macedonian');
INSERT INTO tLanguage (langId, sprache) VALUES (25, 'Welsh');
INSERT INTO tLanguage (langId, sprache) VALUES (26, 'Somali');
INSERT INTO tLanguage (langId, sprache) VALUES (27, 'Dhivehi');
INSERT INTO tLanguage (langId, sprache) VALUES (28, 'Luxembourgish');
INSERT INTO tLanguage (langId, sprache) VALUES (29, 'Malagasy');
INSERT INTO tLanguage (langId, sprache) VALUES (30, 'Afrikaans');


INSERT INTO tInfo (titel, isbn) VALUES ('A Gathering of Eagles', '488583830-4');
INSERT INTO tInfo (titel, isbn) VALUES ('That Sugar Film', '362531301-4');
INSERT INTO tInfo (titel, isbn) VALUES ('Hurricane Express, The', '640692296-4');
INSERT INTO tInfo (titel, isbn) VALUES ('Uprising', '010679329-2');
INSERT INTO tInfo (titel, isbn) VALUES ('Get Carter', '767892649-9');
INSERT INTO tInfo (titel, isbn) VALUES ('So I Married an Axe Murderer', '922766150-6');
INSERT INTO tInfo (titel, isbn) VALUES ('Man for All Seasons, A', '151836899-9');
INSERT INTO tInfo (titel, isbn) VALUES ('Simpsons: The Longest Daycare, The', '628372362-4');
INSERT INTO tInfo (titel, isbn) VALUES ('Stormheart', '442844197-5');
INSERT INTO tInfo (titel, isbn) VALUES ('Dead in Tombstone', '583950960-4');
INSERT INTO tInfo (titel, isbn) VALUES ('Modern Boy (Modeon boi)', '745075236-0');
INSERT INTO tInfo (titel, isbn) VALUES ('Zindagi Na Milegi Dobara', '678827465-7');
INSERT INTO tInfo (titel, isbn) VALUES ('Entertaining Angels: The Dorothy Day Story', '616439532-1');
INSERT INTO tInfo (titel, isbn) VALUES ('Armadillo', '214937612-1');
INSERT INTO tInfo (titel, isbn) VALUES ('Fear, The', '812932974-3');
INSERT INTO tInfo (titel, isbn) VALUES ('Silence, The (Das letzte Schweigen)', '247967918-7');
INSERT INTO tInfo (titel, isbn) VALUES ('Queen of the Amazons', '382851626-2');
INSERT INTO tInfo (titel, isbn) VALUES ('Inside', '782337845-0');
INSERT INTO tInfo (titel, isbn) VALUES ('Closed Curtain', '966384377-2');
INSERT INTO tInfo (titel, isbn) VALUES ('Envy (Kiskanmak)', '617839269-9');
INSERT INTO tInfo (titel, isbn) VALUES ('Pippi on the Run (På rymmen med Pippi Långstrump)', '871748176-7');
INSERT INTO tInfo (titel, isbn) VALUES ('Last Life in the Universe (Ruang rak noi nid mahasan)', '558416067-9');
INSERT INTO tInfo (titel, isbn) VALUES ('Babette Goes to War', '122500330-X');
INSERT INTO tInfo (titel, isbn) VALUES ('Film Unfinished, A (Shtikat Haarchion)', '598517212-0');
INSERT INTO tInfo (titel, isbn) VALUES ('Lady Oscar', '421552961-1');
INSERT INTO tInfo (titel, isbn) VALUES ('Brother Orchid', '613163927-2');
INSERT INTO tInfo (titel, isbn) VALUES ('Dragon Tiger Gate (Lung fu moon)', '185975004-4');
INSERT INTO tInfo (titel, isbn) VALUES ('Burrowing (Man tänker sitt)', '979313362-7');
INSERT INTO tInfo (titel, isbn) VALUES ('Monster in Paris, A (Un monstre à Paris)', '122530552-7');
INSERT INTO tInfo (titel, isbn) VALUES ('I as in Icarus (I... comme Icare)', '937993984-1');
INSERT INTO tInfo (titel, isbn) VALUES ('Mistress', '638914481-4');
INSERT INTO tInfo (titel, isbn) VALUES ('On Dangerous Ground', '910577607-4');
INSERT INTO tInfo (titel, isbn) VALUES ('First Daughter', '166298263-1');
INSERT INTO tInfo (titel, isbn) VALUES ('A Home at the End of the World', '553749871-5');
INSERT INTO tInfo (titel, isbn) VALUES ('Replacement Killers, The', '277760251-4');
INSERT INTO tInfo (titel, isbn) VALUES ('Gangster No. 1', '297046685-6');
INSERT INTO tInfo (titel, isbn) VALUES ('Ice Rink, The (La patinoire)', '028020159-1');
INSERT INTO tInfo (titel, isbn) VALUES ('Poker Club, The', '629636325-7');
INSERT INTO tInfo (titel, isbn) VALUES ('Whispers in the Dark', '462789854-1');
INSERT INTO tInfo (titel, isbn) VALUES ('M. Hulot’s Holiday (Mr. Hulot''s Holiday) (Vacances de Monsieur Hulot, Les)', '728816863-8');
INSERT INTO tInfo (titel, isbn) VALUES ('Class of 1984', '952058507-9');
INSERT INTO tInfo (titel, isbn) VALUES ('Ice Castles', '360924809-2');
INSERT INTO tInfo (titel, isbn) VALUES ('Muppet Family Christmas, A', '828551575-3');
INSERT INTO tInfo (titel, isbn) VALUES ('Come Undone (Presque Rien)', '577219806-8');
INSERT INTO tInfo (titel, isbn) VALUES ('Sacrifice, The (Offret - Sacraficatio)', '954820772-9');
INSERT INTO tInfo (titel, isbn) VALUES ('It''s a Boy Girl Thing', '445342847-2');
INSERT INTO tInfo (titel, isbn) VALUES ('Prairie Love', '535072000-7');
INSERT INTO tInfo (titel, isbn) VALUES ('Cannibal Holocaust', '680577565-5');
INSERT INTO tInfo (titel, isbn) VALUES ('Disco Pigs', '705806475-X');
INSERT INTO tInfo (titel, isbn) VALUES ('Cold Fever (Á köldum klaka)', '296795016-5');

INSERT INTO tAvailability (availableId, verfuegbarkeit) VALUES (1, FALSE);
INSERT INTO tAvailability (availableId, verfuegbarkeit) VALUES (2, TRUE);

INSERT INTO tPublisher (verlagsBezeichnung, telefonnummer, mailadresse, addrStrasse, addrNummer, addrPLZ, addrOrt, addrLand, nameKontaktPers, vornameKontaktPers) VALUES ('Feest-Johnson', '+257 (831) 695-8086', 'ealentyev0@spiegel.de', 'Birchwood', '5', '67 896', 'Aasdk', 'BI', 'Alentyev', 'Ellen');
INSERT INTO tPublisher (verlagsBezeichnung, telefonnummer, mailadresse, addrStrasse, addrNummer, addrPLZ, addrOrt, addrLand, nameKontaktPers, vornameKontaktPers) VALUES ('Ledner-Gerlach', '+46 (153) 803-4568', 'ldacosta1@last.fm', 'Eagle Crest', '38684', '531 85', 'Västra Götaland', 'SE', 'Da Costa', 'Lydie');
INSERT INTO tPublisher (verlagsBezeichnung, telefonnummer, mailadresse, addrStrasse, addrNummer, addrPLZ, addrOrt, addrLand, nameKontaktPers, vornameKontaktPers) VALUES ('Schaden and Sons', '+420 (105) 686-8671', 'acassin2@blogger.com', 'Barnett', '22', '765 02', 'Uztajn', 'CZ', 'Cassin', 'Aloisia');
INSERT INTO tPublisher (verlagsBezeichnung, telefonnummer, mailadresse, addrStrasse, addrNummer, addrPLZ, addrOrt, addrLand, nameKontaktPers, vornameKontaktPers) VALUES ('Erdman-Boyer', '+46 (972) 826-0378', 'espencelayh3@washingtonpost.com', 'Del Mar', '89', '501 83', 'Västra Götaland', 'SE', 'Spencelayh', 'Even');
INSERT INTO tPublisher (verlagsBezeichnung, telefonnummer, mailadresse, addrStrasse, addrNummer, addrPLZ, addrOrt, addrLand, nameKontaktPers, vornameKontaktPers) VALUES ('Lang, Bogan and Lakin', '+62 (438) 743-3255', 'kgorch4@msn.com', 'Bartelt', '99', '9812 98', 'Waskjed', 'ID', 'Gorch', 'Karly');
INSERT INTO tPublisher (verlagsBezeichnung, telefonnummer, mailadresse, addrStrasse, addrNummer, addrPLZ, addrOrt, addrLand, nameKontaktPers, vornameKontaktPers) VALUES ('Block, King and Gislason', '+385 (593) 569-9431', 'sgantzman5@ow.ly', 'Farmco', '18542', '51242', 'Muzahsd', 'HR', 'Gantzman', 'Saundra');
INSERT INTO tPublisher (verlagsBezeichnung, telefonnummer, mailadresse, addrStrasse, addrNummer, addrPLZ, addrOrt, addrLand, nameKontaktPers, vornameKontaktPers) VALUES ('Labadie, Glover and Haag', '+420 (421) 735-1146', 'llynde6@pagesperso-orange.fr', 'Bartillon', '307', '735 32', 'Clköajse', 'CZ', 'Lynde', 'Lonnie');
INSERT INTO tPublisher (verlagsBezeichnung, telefonnummer, mailadresse, addrStrasse, addrNummer, addrPLZ, addrOrt, addrLand, nameKontaktPers, vornameKontaktPers) VALUES ('Will-Von', '+1 (434) 217-8161', 'gbubbear7@dailymail.co.uk', 'La Follette', '66', '22908', 'Virginia', 'US', 'Bubbear', 'Giraud');
INSERT INTO tPublisher (verlagsBezeichnung, telefonnummer, mailadresse, addrStrasse, addrNummer, addrPLZ, addrOrt, addrLand, nameKontaktPers, vornameKontaktPers) VALUES ('Connelly and Sons', '+380 (833) 705-5179', 'blippatt8@mtv.com', 'Cambridge', '95823', '7890', 'Tzujnm', 'UA', 'Lippatt', 'Bartolemo');
INSERT INTO tPublisher (verlagsBezeichnung, telefonnummer, mailadresse, addrStrasse, addrNummer, addrPLZ, addrOrt, addrLand, nameKontaktPers, vornameKontaktPers) VALUES ('Gutkowski-Lemke', '+970 (148) 365-9903', 'jbogue9@list-manage.com', 'Maple', '3', '67812', 'Gvgbkl', 'PS', 'Bogue', 'Julee');
INSERT INTO tPublisher (verlagsBezeichnung, telefonnummer, mailadresse, addrStrasse, addrNummer, addrPLZ, addrOrt, addrLand, nameKontaktPers, vornameKontaktPers) VALUES ('Becker-Murazik', '+30 (371) 274-7270', 'lleemana@facebook.com', 'Myrtle', '33', '162798', 'Klöj Aas', 'GR', 'Leeman', 'Ly');
INSERT INTO tPublisher (verlagsBezeichnung, telefonnummer, mailadresse, addrStrasse, addrNummer, addrPLZ, addrOrt, addrLand, nameKontaktPers, vornameKontaktPers) VALUES ('Boyle-Okuneva', '+20 (934) 168-5019', 'bbeckensallb@cyberchimps.com', 'Del Mar', '3', '809132', 'Öljkas', 'EG', 'Beckensall', 'Britte');
INSERT INTO tPublisher (verlagsBezeichnung, telefonnummer, mailadresse, addrStrasse, addrNummer, addrPLZ, addrOrt, addrLand, nameKontaktPers, vornameKontaktPers) VALUES ('Paucek LLC', '+374 (895) 237-1381', 'sdeliac@yahoo.com', 'Hudson', '363', '80149', 'Tlkaöl', 'AM', 'D','Elia', 'See');
INSERT INTO tPublisher (verlagsBezeichnung, telefonnummer, mailadresse, addrStrasse, addrNummer, addrPLZ, addrOrt, addrLand, nameKontaktPers, vornameKontaktPers) VALUES ('Kovacek Group', '+972 (197) 911-0796', 'wwhistond@senate.gov', 'Saint Paul', '9526', '43560', 'LKéJ Aed', 'IL', 'Whiston', 'Woodrow');
INSERT INTO tPublisher (verlagsBezeichnung, telefonnummer, mailadresse, addrStrasse, addrNummer, addrPLZ, addrOrt, addrLand, nameKontaktPers, vornameKontaktPers) VALUES ('Hahn Group', '+63 (317) 336-4572', 'lmurre@blog.com', 'Glendale', '441', '2402', 'Kaneiemä', 'PH', 'Murr', 'Leanora');
INSERT INTO tPublisher (verlagsBezeichnung, telefonnummer, mailadresse, addrStrasse, addrNummer, addrPLZ, addrOrt, addrLand, nameKontaktPers, vornameKontaktPers) VALUES ('Murphy-Walter', '+62 (628) 825-3139', 'bspickf@weibo.com', 'Fair Oaks', '29857', '128709', 'Mnaikmeu', 'ID', 'Spick', 'Bobbette');
INSERT INTO tPublisher (verlagsBezeichnung, telefonnummer, mailadresse, addrStrasse, addrNummer, addrPLZ, addrOrt, addrLand, nameKontaktPers, vornameKontaktPers) VALUES ('Gerhold Group', '+63 (959) 395-7603', 'svalesg@comsenz.com', 'Oneill', '044', '8301', 'Mauekruö', 'PH', 'Vales', 'Stinky');
INSERT INTO tPublisher (verlagsBezeichnung, telefonnummer, mailadresse, addrStrasse, addrNummer, addrPLZ, addrOrt, addrLand, nameKontaktPers, vornameKontaktPers) VALUES ('Kohler-Luettgen', '+55 (700) 828-7293', 'wviccarsh@gravatar.com', 'David', '42387', '77645-000', 'Naeinei', 'BR', 'Viccars', 'Willem');
INSERT INTO tPublisher (verlagsBezeichnung, telefonnummer, mailadresse, addrStrasse, addrNummer, addrPLZ, addrOrt, addrLand, nameKontaktPers, vornameKontaktPers) VALUES ('Deckow, Ward and Graham', '+62 (383) 331-5726', 'kdecourcyi@ucoz.ru', 'Columbus', '9861', '458632', 'Neinepoän', 'ID', 'de Courcy', 'Kendrick');
INSERT INTO tPublisher (verlagsBezeichnung, telefonnummer, mailadresse, addrStrasse, addrNummer, addrPLZ, addrOrt, addrLand, nameKontaktPers, vornameKontaktPers) VALUES ('MacGyver-Renner', '+62 (443) 308-8196', 'gmaccullochj@yahoo.com', 'Shoshone', '51', '10573', 'Nasdlköje', 'ID', 'MacCulloch', 'Gusella');
INSERT INTO tPublisher (verlagsBezeichnung, telefonnummer, mailadresse, addrStrasse, addrNummer, addrPLZ, addrOrt, addrLand, nameKontaktPers, vornameKontaktPers) VALUES ('Towne, Gusikowski and Howe', '+52 (811) 952-4861', 'nheamk@ca.gov', 'Blackbird', '98', '45306', 'Jalisco', 'MX', 'Heam', 'Nealy');
INSERT INTO tPublisher (verlagsBezeichnung, telefonnummer, mailadresse, addrStrasse, addrNummer, addrPLZ, addrOrt, addrLand, nameKontaktPers, vornameKontaktPers) VALUES ('Huel-McDermott', '+7 (682) 897-7505', 'bmeasorl@dot.gov', 'Birchwood', '4916', '404109', 'Jemknceza', 'RU', 'Measor', 'Barbe');
INSERT INTO tPublisher (verlagsBezeichnung, telefonnummer, mailadresse, addrStrasse, addrNummer, addrPLZ, addrOrt, addrLand, nameKontaktPers, vornameKontaktPers) VALUES ('Fritsch, Crist and Weber', '+62 (688) 703-7036', 'hmedforthm@51.la', 'Tony', '64799', '20567', 'Nemüamöer', 'ID', 'Medforth', 'Husain');
INSERT INTO tPublisher (verlagsBezeichnung, telefonnummer, mailadresse, addrStrasse, addrNummer, addrPLZ, addrOrt, addrLand, nameKontaktPers, vornameKontaktPers) VALUES ('Bashirian Inc', '+86 (944) 731-4845', 'kbuncomn@delicious.com', 'Linden', '33112', '39', 'Nlökeaneun', 'CN', 'Buncom', 'Kaspar');
INSERT INTO tPublisher (verlagsBezeichnung, telefonnummer, mailadresse, addrStrasse, addrNummer, addrPLZ, addrOrt, addrLand, nameKontaktPers, vornameKontaktPers) VALUES ('Hudson LLC', '+86 (573) 945-1207', 'rmarko@yahoo.com', 'Service', '1241', '3067', 'Huezanmez', 'CN', 'Mark', 'Rainer');
INSERT INTO tPublisher (verlagsBezeichnung, telefonnummer, mailadresse, addrStrasse, addrNummer, addrPLZ, addrOrt, addrLand, nameKontaktPers, vornameKontaktPers) VALUES ('Torp and Sons', '+503 (550) 107-1319', 'emeckiffp@utexas.edu', 'Graedel', '92920', '1493', 'Naekl', 'SV', 'Meckiff', 'Ebenezer');
INSERT INTO tPublisher (verlagsBezeichnung, telefonnummer, mailadresse, addrStrasse, addrNummer, addrPLZ, addrOrt, addrLand, nameKontaktPers, vornameKontaktPers) VALUES ('Gottlieb and Sons', '+351 (665) 226-8774', 'afaraganq@sun.com', 'Schurz', '546', '2890-206', 'Setúbal', 'PT', 'Faragan', 'Antonie');
INSERT INTO tPublisher (verlagsBezeichnung, telefonnummer, mailadresse, addrStrasse, addrNummer, addrPLZ, addrOrt, addrLand, nameKontaktPers, vornameKontaktPers) VALUES ('Stracke, Schneider and Rau', '+62 (121) 548-3727', 'jboxenr@feedburner.com', 'School', '92396', '28949', 'Umeunae', 'ID', 'Boxen', 'Jaymee');
INSERT INTO tPublisher (verlagsBezeichnung, telefonnummer, mailadresse, addrStrasse, addrNummer, addrPLZ, addrOrt, addrLand, nameKontaktPers, vornameKontaktPers) VALUES ('Kilback, Barton and Ziemann', '+7 (536) 313-5153', 'jeptons@studiopress.com', 'Kedzie', '011', '309379', 'Rmzethak', 'RU', 'Epton', 'Joannes');
INSERT INTO tPublisher (verlagsBezeichnung, telefonnummer, mailadresse, addrStrasse, addrNummer, addrPLZ, addrOrt, addrLand, nameKontaktPers, vornameKontaktPers) VALUES ('Schowalter LLC', '+55 (145) 486-2855', 'jpullant@yellowbook.com', 'Riverside', '3', '18500-000', 'Zzkasa', 'BR', 'Pullan', 'Julietta');

